### ISSUE TITLE
Feeding adsbexchange issues

### ISSUE THREAD

**Issue by tushroy** [sdr-enthusiasts/docker-adsb-ultrafeeder#143]
After adding following config
`      - ULTRAFEEDER_CONFIG=
          adsb,feed1.adsbexchange.com,30004,beast_reduce_plus_out,uuid=${ADSBX_UUID};
          mlat,feed.adsbexchange.com,31090,39008,uuid=${ADSBX_UUID};`
ultrafeeder starts feeding to adsbexchange, confirmed from docker logs, but https://adsbexchange.com/myip/ shows no feed connected.

resulting unable to link receiver to adsbexchange account.

**Comment by tushroy** [comment]
Feeder Statistics page comes after a while but still no feed found.
![image](https://github.com/user-attachments/assets/e1e6833e-f71d-4904-9643-c50345b26061)

**Comment by kx1t** [comment]
That AdsbExchange link will only work if your browse there from the same network as your feeder computer (public IP address of `103.72.212.97` in your case). That may not be the case.

In any case, you should be able to see your ADS-B map and your MLAT status with the links that are shown when you provide this command on your Linux command line: `docker logs ultrafeeder | grep Anywhere`

```bash
$ docker logs ultrafeeder | grep Anywhere
[2024-09-17 14:01:38.990][adsbx-stats] Your AdsbExchange Anywhere Map URL is https://globe.adsbexchange.com/?feed=xxxxxxxxxx
[2024-09-17 14:01:39.078][adsbx-stats] Your AdsbExchange Anywhere Stats URL is https://www.adsbexchange.com/api/feeders/?feed=xxxxxxxxxx&t=1234567890
```

If that doesn't work, you should carefully review the AdsbExchange related logs of your ultrafeeder container for any issues: `docker logs ultrafeeder | grep -i adsbexchange`

**Comment by kx1t** [comment]
From your docker-compose config and your logs, everything looks OK. I assume that the two AdsbExchange Anywhere URLs also look like there are results? If so, I have no idea what's going wrong for you.

I also checked my own station (very similar setup feeding Adsbx from Ultrafeeder, on an x86 machine on my local network) and for me, the myip webpage renders correctly, see below. I still suspect that there is somehow a mismatch between the public IP address of your browser's computer and the one for your receiver computer. Are you sure you aren't using a VPN on your browser's computer or something similar?

One last thing you can check -- try `curl ifconfig.me` and see if it returns the same IP as the Adsbx myip page renders (`103.72.212.103` in your screenshot above)

![image](https://github.com/user-attachments/assets/50d888a5-900c-41f8-a5cd-c3f2672cc5d2)

**Comment by tushroy** [comment]
@kx1t I think I have found the issue. My ISP is routing traffic for adsbexchange.com (Cloudflare) and feed1.adsbexchange.com (AWS) in 2 different routes. As a result adsbexchange.com/myip doesn't see the IP routed through feed1.adsbexchange.com.
