### ISSUE TITLE
Export data from readsb to Prometheus has broken after Prometheus update

### ISSUE THREAD

**Issue by freeball155** [sdr-enthusiasts/docker-adsb-ultrafeeder#160]
Hello.

I use Prometheus and Grafana for visualization. Tonight after Prometheus update by watchtower most of the graphs broke. In Prometheus logs there was this message:
**time=2024-11-15T08:10:57.199Z level=ERROR source=scrape.go:1585 msg="Failed to determine correct type of scrape target." component="scrape manager" scrape_pool=ultrafeeder target=http://ultrafeeder:9274/metrics content_type=application/octet-stream fallback_media_type="" err="received unsupported Content-Type \"application/octet-stream\" and no fallback_scrape_protocol specified for target"**

I was able to fix this problem by adding the following line to prometheus.yml config:
  - job_name: "ultrafeeder"
    **fallback_scrape_protocol: "PrometheusText1.0.0"**
    static_configs:
      - targets: ["ultrafeeder:9273", "ultrafeeder:9274"]

Perhaps it is worth adding this to the [documentation](https://github.com/sdr-enthusiasts/docker-adsb-ultrafeeder/blob/main/README-grafana.md#step-3-configuring-prometheus).

**Comment by wiedehopf** [comment]
This is a workaround.

Better to adjust the served mimetype:

https://github.com/sdr-enthusiasts/docker-tar1090/pull/243
https://github.com/sdr-enthusiasts/docker-tar1090/pull/243/commits/1ac42b8ed5f8a9479547c14e2fd479504dd4f069

Please re-test without the workaround once the PR is merged and an updated image built.
(ultrafeeder builds on top of tar1090 so this change will affect ultrafeeder)
