### ISSUE TITLE
InfluxDB - No Org

### ISSUE THREAD

**Issue by bacco007** [sdr-enthusiasts/docker-adsb-ultrafeeder#5]
I've tried to enable the InfluxDB functionality, but getting error reports that I need to provide an Org or OrgId

There does not appear to be an environment variable to set this detail

```
[telegraf] 2023-04-01T03:40:03Z E! [outputs.influxdb_v2] Failed to write metric to adsb_tbsh (will be dropped: 400 Bad Request): invalid: Please provide either orgID or org
```

**Comment by kx1t** [comment]
Hi, sorry for that, could you open an issue at https://github.com/sdr-enthusiasts/docker-tar1090/issues for that? The ultrafeeder container simply pulls in the Telegraf functionality from the tar1090 container. Thanks!

**Comment by bacco007** [comment]
No problem!
