### ISSUE TITLE
Configuring data source and dashboard in Grafana does not work

### ISSUE THREAD

**Issue by BMeyendriesch** [sdr-enthusiasts/docker-adsb-ultrafeeder#66]
When trying to connect grafana to influxdb following exactly your Guide "Configuring data source and dashboard in Grafana" I always end with a grafana error message: "unauthorized: unauthorized access error reading buckets". 

My docker container use:

InfluxDB v2.7.5 (git: 09a9607fd9) build_date: 2024-01-05T17:17:15Z
Grafana Version 10.3.3 (commit: 252761264e22ece57204b327f9130d3b44592c01, branch: HEAD)

What's going wrong here?

**Comment by kx1t** [comment]
Sorry - very little experience configuring InfluxDB; if you'd want to switch to Prometheus, there are instructions on how to configure things here: https://github.com/sdr-enthusiasts/docker-adsb-ultrafeeder/blob/main/README-grafana.md
