### ISSUE TITLE
ultrafeeder unrecognized option error

### ISSUE THREAD

**Issue by Peterkal2112** [sdr-enthusiasts/docker-adsb-ultrafeeder#74]
Today after 20:40 I registered an error in ultrafeeder on both of my feeders, one on raspberry pi 3 arm64 docker, other one on debian amd64 docker...

This is from docker compose up running and restarting the compose hour after....

```
[2024-03-29 21:44:12.513][readsb] /usr/local/bin/readsb: unrecognized option '--write-json-globe-index --write-globe-history /var/globe_history'
[2024-03-29 21:44:12.513][readsb] Try `/usr/local/bin/readsb --help' or `/usr/local/bin/readsb --usage' for more information.
[2024-03-29 21:44:12.513][readsb] Error parsing the given command line parameters, check readsb --usage and readsb --help for valid parameters.
```

I had to comment out a line in my docker compose file that should collect airplane data to files:

`- READSB_EXTRA_ARGS=--write-json-globe-index --write-globe-history /var/globe_history`

after this it started to work.... 

I did nothing to it...

These screenshot are from two different feeders and the time that it stopped work is the same...

![msedge_4POlZGvWGs](https://github.com/sdr-enthusiasts/docker-adsb-ultrafeeder/assets/63470836/ff6bb304-2119-4b4c-ba1b-434fa1356d11)

![msedge_YojX6JxViF](https://github.com/sdr-enthusiasts/docker-adsb-ultrafeeder/assets/63470836/faff0a9a-b247-41b5-8604-876ccf9cbdbe)

I have also installed a watchtower that watching every 60 second all containers if they are updated, and if they are not, it should update them.... (I assume, maybe some update happened and new version does not have theese ``unrecognized option '--write-json-globe-index --write-globe-history /var/globe_history'`` extra args but that is just my assumption which can be false....)

**Comment by kx1t** [comment]
There was a bug for a few minutes that stopped some functionality from working properly, but I don't think that was related to what you are seeing. In any case - the current container is stable.

Also, I'd think that 60 seconds is very very short for WatchTower. Most people check once per day; and I have an extreme case where I check every 5 minutes. Please consider extending that time a but.

Last - I checked by adding your parameters to my latest build and it seems to work fine now
